version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --no-cache-dir -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo start server on `date`
      - export FLASK_ENV=development 
      - export FLASK_RUN_HOST=0.0.0.0
      - flask run --port=8000
